/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RailMenu: typeof import('./components/RailMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDetailsDialog: typeof import('./components/UserDetailsDialog.vue')['default']
    UserFormDialog: typeof import('./components/UserFormDialog.vue')['default']
    UsersTable: typeof import('./components/UsersTable.vue')['default']
  }
}
